package com.silencer.entity;
// Generated Aug 5, 2020 10:04:54 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SilencerSize generated by hbm2java
 */
@Entity
@Table(name = "silencer_tread_size", catalog = "freydevikdb")
public class SilencerTreadSize implements java.io.Serializable {

	private Integer silencerSizeId;
	private String treadSize;
	

	public SilencerTreadSize() {
	}

	public SilencerTreadSize(String treadSize) {
		this.treadSize = treadSize;
		
	}
	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "silencer_tread_size_id", unique = true, nullable = false)
	public Integer getSilencerSizeId() {
		return this.silencerSizeId;
	}

	public void setSilencerSizeId(Integer silencerSizeId) {
		this.silencerSizeId = silencerSizeId;
	}

	@Column(name = "tread_size", nullable = true, length = 45)
	public String getTreadSize() {
		return this.treadSize;
	}

	public void setTreadSize(String treadSize) {
		this.treadSize = treadSize;
	}



}
