/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-08-24 08:30:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.frontend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class NewFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\" />\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("        <meta name=\"description\" content=\"\" />\r\n");
      out.write("        <meta name=\"author\" content=\"\" />\r\n");
      out.write("        <title>Freelancer - Start Bootstrap Theme</title>\r\n");
      out.write("        <!-- Favicon-->\r\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"assets/img/favicon.ico\" />\r\n");
      out.write("        <!-- Font Awesome icons (free version)-->\r\n");
      out.write("        <script src=\"https://use.fontawesome.com/releases/v5.13.0/js/all.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <!-- Google fonts-->\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\r\n");
      out.write("        <link href=\"css/styles.css\" rel=\"stylesheet\" />\r\n");
      out.write("    </head>\r\n");
      out.write("    <body id=\"page-top\">\r\n");
      out.write("        <!-- Navigation-->\r\n");
      out.write("        <nav class=\"navbar navbar-expand-lg bg-secondary text-uppercase fixed-top\" id=\"mainNav\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <a class=\"navbar-brand js-scroll-trigger\" href=\"#page-top\">Start Bootstrap</a>\r\n");
      out.write("                <button class=\"navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                    Menu\r\n");
      out.write("                    <i class=\"fas fa-bars\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("                    <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("                        <li class=\"nav-item mx-0 mx-lg-1\"><a class=\"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger\" href=\"#portfolio\">Portfolio</a></li>\r\n");
      out.write("                        <li class=\"nav-item mx-0 mx-lg-1\"><a class=\"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger\" href=\"#about\">About</a></li>\r\n");
      out.write("                        <li class=\"nav-item mx-0 mx-lg-1\"><a class=\"nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger\" href=\"#contact\">Contact</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- Masthead-->\r\n");
      out.write("        <header class=\"masthead bg-primary text-white text-center\">\r\n");
      out.write("            <div class=\"container d-flex align-items-center flex-column\">\r\n");
      out.write("                <!-- Masthead Avatar Image-->\r\n");
      out.write("                <img class=\"masthead-avatar mb-5\" src=\"assets/img/avataaars.svg\" alt=\"\" />\r\n");
      out.write("                <!-- Masthead Heading-->\r\n");
      out.write("                <h1 class=\"masthead-heading text-uppercase mb-0\">Start Bootstrap</h1>\r\n");
      out.write("                <!-- Icon Divider-->\r\n");
      out.write("                <div class=\"divider-custom divider-light\">\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Masthead Subheading-->\r\n");
      out.write("                <p class=\"masthead-subheading font-weight-light mb-0\">Graphic Artist - Web Designer - Illustrator</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- Portfolio Section-->\r\n");
      out.write("        <section class=\"page-section portfolio\" id=\"portfolio\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- Portfolio Section Heading-->\r\n");
      out.write("                <h2 class=\"page-section-heading text-center text-uppercase text-secondary mb-0\">Portfolio</h2>\r\n");
      out.write("                <!-- Icon Divider-->\r\n");
      out.write("                <div class=\"divider-custom\">\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Portfolio Grid Items-->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <!-- Portfolio Item 1-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal1\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/cabin.png\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Portfolio Item 2-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal2\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/cake.png\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Portfolio Item 3-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal3\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/circus.png\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Portfolio Item 4-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal4\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/game.png\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Portfolio Item 5-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5 mb-md-0\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal5\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/safe.png\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Portfolio Item 6-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal6\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/submarine.png\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- About Section-->\r\n");
      out.write("        <section class=\"page-section bg-primary text-white mb-0\" id=\"about\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- About Section Heading-->\r\n");
      out.write("                <h2 class=\"page-section-heading text-center text-uppercase text-white\">About</h2>\r\n");
      out.write("                <!-- Icon Divider-->\r\n");
      out.write("                <div class=\"divider-custom divider-light\">\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- About Section Content-->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-4 ml-auto\"><p class=\"lead\">Freelancer is a free bootstrap theme created by Start Bootstrap. The download includes the complete source files including HTML, CSS, and JavaScript as well as optional SASS stylesheets for easy customization.</p></div>\r\n");
      out.write("                    <div class=\"col-lg-4 mr-auto\"><p class=\"lead\">You can create your own custom avatar for the masthead, change the icon in the dividers, and add your email address to the contact form to make it fully functional!</p></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- About Section Button-->\r\n");
      out.write("                <div class=\"text-center mt-4\">\r\n");
      out.write("                    <a class=\"btn btn-xl btn-outline-light\" href=\"https://startbootstrap.com/themes/freelancer/\">\r\n");
      out.write("                        <i class=\"fas fa-download mr-2\"></i>\r\n");
      out.write("                        Free Download!\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Contact Section-->\r\n");
      out.write("        <section class=\"page-section\" id=\"contact\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- Contact Section Heading-->\r\n");
      out.write("                <h2 class=\"page-section-heading text-center text-uppercase text-secondary mb-0\">Contact Me</h2>\r\n");
      out.write("                <!-- Icon Divider-->\r\n");
      out.write("                <div class=\"divider-custom\">\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Contact Section Form-->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col-lg-8 mx-auto\">\r\n");
      out.write("                        <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19.-->\r\n");
      out.write("                        <form id=\"contactForm\" name=\"sentMessage\" novalidate=\"novalidate\">\r\n");
      out.write("                            <div class=\"control-group\">\r\n");
      out.write("                                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\r\n");
      out.write("                                    <label>Name</label>\r\n");
      out.write("                                    <input class=\"form-control\" id=\"name\" type=\"text\" placeholder=\"Name\" required=\"required\" data-validation-required-message=\"Please enter your name.\" />\r\n");
      out.write("                                    <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"control-group\">\r\n");
      out.write("                                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\r\n");
      out.write("                                    <label>Email Address</label>\r\n");
      out.write("                                    <input class=\"form-control\" id=\"email\" type=\"email\" placeholder=\"Email Address\" required=\"required\" data-validation-required-message=\"Please enter your email address.\" />\r\n");
      out.write("                                    <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"control-group\">\r\n");
      out.write("                                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\r\n");
      out.write("                                    <label>Phone Number</label>\r\n");
      out.write("                                    <input class=\"form-control\" id=\"phone\" type=\"tel\" placeholder=\"Phone Number\" required=\"required\" data-validation-required-message=\"Please enter your phone number.\" />\r\n");
      out.write("                                    <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"control-group\">\r\n");
      out.write("                                <div class=\"form-group floating-label-form-group controls mb-0 pb-2\">\r\n");
      out.write("                                    <label>Message</label>\r\n");
      out.write("                                    <textarea class=\"form-control\" id=\"message\" rows=\"5\" placeholder=\"Message\" required=\"required\" data-validation-required-message=\"Please enter a message.\"></textarea>\r\n");
      out.write("                                    <p class=\"help-block text-danger\"></p>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <br />\r\n");
      out.write("                            <div id=\"success\"></div>\r\n");
      out.write("                            <div class=\"form-group\"><button class=\"btn btn-primary btn-xl\" id=\"sendMessageButton\" type=\"submit\">Send</button></div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- Footer-->\r\n");
      out.write("        <footer class=\"footer text-center\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <!-- Footer Location-->\r\n");
      out.write("                    <div class=\"col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-4\">Location</h4>\r\n");
      out.write("                        <p class=\"lead mb-0\">\r\n");
      out.write("                            2215 John Daniel Drive\r\n");
      out.write("                            <br />\r\n");
      out.write("                            Clark, MO 65243\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Footer Social Icons-->\r\n");
      out.write("                    <div class=\"col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-4\">Around the Web</h4>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i class=\"fab fa-fw fa-facebook-f\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i class=\"fab fa-fw fa-twitter\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i class=\"fab fa-fw fa-linkedin-in\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social mx-1\" href=\"#!\"><i class=\"fab fa-fw fa-dribbble\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Footer About Text-->\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-4\">About Freelancer</h4>\r\n");
      out.write("                        <p class=\"lead mb-0\">\r\n");
      out.write("                            Freelance is a free to use, MIT licensed Bootstrap theme created by\r\n");
      out.write("                            <a href=\"http://startbootstrap.com\">Start Bootstrap</a>\r\n");
      out.write("                            .\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        <!-- Copyright Section-->\r\n");
      out.write("        <div class=\"copyright py-4 text-center text-white\">\r\n");
      out.write("            <div class=\"container\"><small>Copyright © Your Website 2020</small></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes)-->\r\n");
      out.write("        <div class=\"scroll-to-top d-lg-none position-fixed\">\r\n");
      out.write("            <a class=\"js-scroll-trigger d-block text-center text-white rounded\" href=\"#page-top\"><i class=\"fa fa-chevron-up\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio Modals-->\r\n");
      out.write("        <!-- Portfolio Modal 1-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"portfolioModal1Label\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\" role=\"document\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\"><i class=\"fas fa-times\"></i></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"modal-body text-center\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\" id=\"portfolioModal1Label\">Log Cabin</h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\">\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    <img class=\"img-fluid rounded mb-5\" src=\"assets/img/portfolio/cabin.png\" alt=\"\" />\r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\">\r\n");
      out.write("                                        <i class=\"fas fa-times fa-fw\"></i>\r\n");
      out.write("                                        Close Window\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio Modal 2-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal2\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"portfolioModal2Label\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\" role=\"document\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\"><i class=\"fas fa-times\"></i></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"modal-body text-center\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\" id=\"portfolioModal2Label\">Tasty Cake</h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\">\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    <img class=\"img-fluid rounded mb-5\" src=\"assets/img/portfolio/cake.png\" alt=\"\" />\r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\">\r\n");
      out.write("                                        <i class=\"fas fa-times fa-fw\"></i>\r\n");
      out.write("                                        Close Window\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio Modal 3-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal3\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"portfolioModal3Label\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\" role=\"document\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\"><i class=\"fas fa-times\"></i></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"modal-body text-center\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\" id=\"portfolioModal3Label\">Circus Tent</h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\">\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    <img class=\"img-fluid rounded mb-5\" src=\"assets/img/portfolio/circus.png\" alt=\"\" />\r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\">\r\n");
      out.write("                                        <i class=\"fas fa-times fa-fw\"></i>\r\n");
      out.write("                                        Close Window\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio Modal 4-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal4\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"portfolioModal4Label\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\" role=\"document\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\"><i class=\"fas fa-times\"></i></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"modal-body text-center\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\" id=\"portfolioModal4Label\">Controller</h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\">\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    <img class=\"img-fluid rounded mb-5\" src=\"assets/img/portfolio/game.png\" alt=\"\" />\r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\">\r\n");
      out.write("                                        <i class=\"fas fa-times fa-fw\"></i>\r\n");
      out.write("                                        Close Window\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio Modal 5-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal5\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"portfolioModal5Label\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\" role=\"document\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\"><i class=\"fas fa-times\"></i></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"modal-body text-center\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\" id=\"portfolioModal5Label\">Locked Safe</h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\">\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    <img class=\"img-fluid rounded mb-5\" src=\"assets/img/portfolio/safe.png\" alt=\"\" />\r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\">\r\n");
      out.write("                                        <i class=\"fas fa-times fa-fw\"></i>\r\n");
      out.write("                                        Close Window\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Portfolio Modal 6-->\r\n");
      out.write("        <div class=\"portfolio-modal modal fade\" id=\"portfolioModal6\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"portfolioModal6Label\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-xl\" role=\"document\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <button class=\"close\" type=\"button\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\"><i class=\"fas fa-times\"></i></span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <div class=\"modal-body text-center\">\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("                            <div class=\"row justify-content-center\">\r\n");
      out.write("                                <div class=\"col-lg-8\">\r\n");
      out.write("                                    <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                    <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\" id=\"portfolioModal6Label\">Submarine</h2>\r\n");
      out.write("                                    <!-- Icon Divider-->\r\n");
      out.write("                                    <div class=\"divider-custom\">\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                        <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                                        <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!-- Portfolio Modal - Image-->\r\n");
      out.write("                                    <img class=\"img-fluid rounded mb-5\" src=\"assets/img/portfolio/submarine.png\" alt=\"\" />\r\n");
      out.write("                                    <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                    <p class=\"mb-5\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>\r\n");
      out.write("                                    <button class=\"btn btn-primary\" data-dismiss=\"modal\">\r\n");
      out.write("                                        <i class=\"fas fa-times fa-fw\"></i>\r\n");
      out.write("                                        Close Window\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Bootstrap core JS-->\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("        <!-- Third party plugin JS-->\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js\"></script>\r\n");
      out.write("        <!-- Contact form JS-->\r\n");
      out.write("        <script src=\"assets/mail/jqBootstrapValidation.js\"></script>\r\n");
      out.write("        <script src=\"assets/mail/contact_me.js\"></script>\r\n");
      out.write("        <!-- Core theme JS-->\r\n");
      out.write("        <script src=\"js/scripts.js\"></script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
