/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-01 11:44:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.frontend;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class testdynamicform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title></title>\r\n");
      out.write("<script src=\"js/form.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"css/form.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".main{\r\n");
      out.write("border:1px solid #000;\r\n");
      out.write("background:#FAFAFA;\r\n");
      out.write("width:960px;\r\n");
      out.write("height:775px;\r\n");
      out.write("margin:10px auto;\r\n");
      out.write("overflow:auto\r\n");
      out.write("}\r\n");
      out.write(".header{\r\n");
      out.write("background-color:#40B1ED;\r\n");
      out.write("height:70px;\r\n");
      out.write("margin-top:-21px;\r\n");
      out.write("padding-top:10px;\r\n");
      out.write("color:#fff;\r\n");
      out.write("text-align:center;\r\n");
      out.write("border-bottom:1px solid #000\r\n");
      out.write("}\r\n");
      out.write(".name{\r\n");
      out.write("padding:8px 40px;\r\n");
      out.write("font-size:16px;\r\n");
      out.write("font-weight:300;\r\n");
      out.write("background-color:#9acd32;\r\n");
      out.write("border:2px solid gray;\r\n");
      out.write("color:#fff;\r\n");
      out.write("box-shadow:0 0 10px gray;\r\n");
      out.write("margin-bottom:10px;\r\n");
      out.write("margin-top:5px;\r\n");
      out.write("cursor:pointer\r\n");
      out.write("}\r\n");
      out.write("input{\r\n");
      out.write("padding:8px;\r\n");
      out.write("width:22%;\r\n");
      out.write("border:3px solid #ddd;\r\n");
      out.write("box-shadow:0 0 2px;\r\n");
      out.write("margin-bottom:20px\r\n");
      out.write("}\r\n");
      out.write("input[type=submit]{\r\n");
      out.write("border:3px solid #fff;\r\n");
      out.write("background:linear-gradient(#c4fcfc,#02d2fa)\r\n");
      out.write("}\r\n");
      out.write("input[type=submit]:hover{\r\n");
      out.write("background:linear-gradient(#02d2fa,#c4fcfc)\r\n");
      out.write("}\r\n");
      out.write("img{\r\n");
      out.write("margin-top:100px\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("text-decoration:none\r\n");
      out.write("}\r\n");
      out.write(".two{\r\n");
      out.write("text-align:center;\r\n");
      out.write("background-color:#fff;\r\n");
      out.write("width:290px;\r\n");
      out.write("height:593px;\r\n");
      out.write("padding:40px 15px;\r\n");
      out.write("border:1px solid #000;\r\n");
      out.write("border-radius:4px;\r\n");
      out.write("box-shadow:0 0 5px #000;\r\n");
      out.write("float:left;\r\n");
      out.write("margin:20px\r\n");
      out.write("}\r\n");
      out.write(".third{\r\n");
      out.write("background-color:#fff;\r\n");
      out.write("width:575px;\r\n");
      out.write("height:645px;\r\n");
      out.write("padding-top:30px;\r\n");
      out.write("border:1px solid #000;\r\n");
      out.write("border-radius:4px;\r\n");
      out.write("overflow:auto;\r\n");
      out.write("box-shadow:0 0 5px #000;\r\n");
      out.write("float:left;\r\n");
      out.write("margin-top:20px;\r\n");
      out.write("text-align:center\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t<h1></h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"third\">\r\n");
      out.write("\t\t<form action=\"shop_customer\" id=\"mainform\" method=\"get\" name=\"mainform\">\r\n");
      out.write("\t\t<p id=\"myForm\"></p><input type=\"submit\" value=\"Submit\">\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"two\">\r\n");
      out.write("\t\t<button class=\"name\" onclick=\"textBoxCreate()\">New Form</button>\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var i = 1; \r\n");
      out.write("var j = 1;\r\n");
      out.write("var k = 1;\r\n");
      out.write("var l = 1;\r\n");
      out.write("\r\n");
      out.write("function textBoxCreate(){\r\n");
      out.write("\tvar y = document.createElement(\"select\");\r\n");
      out.write("\ty.setAttribute(\"type\", \"text\");\r\n");
      out.write("\ty.setAttribute(\"Placeholder\", \"Tread Size \" + j);\r\n");
      out.write("\ty.setAttribute(\"Name\", \"tread_\" + j);\r\n");
      out.write("\tdocument.getElementById(\"myForm\").appendChild(y);\r\n");
      out.write("\tj++;\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\tvar y = document.createElement(\"select\");\r\n");
      out.write("\ty.setAttribute(\"type\", \"text\");\r\n");
      out.write("\ty.setAttribute(\"Placeholder\", \"Core Size \" + i);\r\n");
      out.write("\ty.setAttribute(\"Name\", \"core_\" + i);\r\n");
      out.write("\tdocument.getElementById(\"myForm\").appendChild(y);\r\n");
      out.write("\ti++;\r\n");
      out.write("\t\r\n");
      out.write("\tvar y = document.createElement(\"select\");\r\n");
      out.write("\ty.setAttribute(\"type\", \"text\");\r\n");
      out.write("\ty.setAttribute(\"Placeholder\", \"total \" + k);\r\n");
      out.write("\ty.setAttribute(\"Name\", \"total\" + k);\r\n");
      out.write("\tdocument.getElementById(\"myForm\").appendChild(y);\r\n");
      out.write("\tk++;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
